# Generated by Django 5.2.6 on 2025-09-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_crypto_fields", "0007_alter_crypt_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypt",
            name="device_modified",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="crypt",
            name="hash",
            field=models.CharField(
                db_index=True, max_length=128, null=True, verbose_name="Hash"
            ),
        ),
    ]
