# Generated by Django 5.2.6 on 2025-09-17 13:10

import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_crypto_fields", "0008_alter_crypt_device_modified_alter_crypt_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypt",
            name="device_created",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="crypt",
            name="hostname_modified",
            field=django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                blank=True,
                help_text="System field. (modified on every save)",
                max_length=50,
                null=True,
                verbose_name="Hostname modified",
            ),
        ),
        migrations.AlterField(
            model_name="crypt",
            name="user_created",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                help_text="Updated by admin.save_model",
                max_length=50,
                null=True,
                verbose_name="user created",
            ),
        ),
        migrations.AlterField(
            model_name="crypt",
            name="user_modified",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                help_text="Updated by admin.save_model",
                max_length=50,
                null=True,
                verbose_name="user modified",
            ),
        ),
    ]
