# Generated by Django 5.2.6 on 2025-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_crypto_fields", "0010_alter_crypt_device_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypt",
            name="algorithm",
            field=models.CharField(db_index=True, default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="crypt",
            name="hash",
            field=models.CharField(
                db_index=True, default="", max_length=128, verbose_name="Hash"
            ),
        ),
        migrations.AlterField(
            model_name="crypt",
            name="mode",
            field=models.CharField(db_index=True, default="", max_length=25),
        ),
    ]
