# Generated by Django 4.1 on 2022-08-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_crypto_fields", "0002_auto_20190303_2341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypt",
            name="cipher_mode",
            field=models.IntegerField(
                help_text="pycryptodomex AES cipher mode (e.g. MODE_CBC)", null=True
            ),
        ),
    ]
