# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_crypto_fields", "0005_auto_20170106_1849")]

    operations = [
        migrations.AlterField(
            model_name="crypt",
            name="hash",
            field=models.CharField(db_index=True, max_length=128, verbose_name="Hash"),
        )
    ]
