# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_crypto_fields", "0007_auto_20170518_1233")]

    operations = [
        migrations.AddField(
            model_name="crypt",
            name="device_created",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="crypt",
            name="device_modified",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name="crypt",
            index=models.Index(
                fields=["hash", "algorithm", "mode"], name="django_cryp_hash_76d13d_idx"
            ),
        ),
    ]
