# Generated by Django 2.0rc1 on 2017-12-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("django_crypto_fields", "0010_keyreference")]

    operations = [migrations.DeleteModel(name="KeyReference")]
